[build-system]
requires = ["flit_core >=3.2,<4","lumache >=0.2.0,<0.3.0"]
build-backend = "flit_core.buildapi"

[project]
name = "8840-utils-docs"
authors = [{name = "Jaiden Grimminck", email = "frc8840@gmail.com"}]
dynamic = ["version", "description"]
